# Generated by Django 5.1 on 2024-08-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationId', models.IntegerField()),
                ('applicant', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=100)),
                ('cnn', models.IntegerField()),
                ('location_description', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=255)),
                ('blocklot', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=20)),
                ('lot', models.CharField(max_length=20)),
                ('permit', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('food_items', models.TextField()),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('schedule', models.URLField(max_length=500)),
                ('noi_sent', models.CharField(blank=True, max_length=50, null=True)),
                ('approved', models.CharField(blank=True, max_length=50, null=True)),
                ('received', models.CharField(blank=True, max_length=50, null=True)),
                ('prior_permit', models.IntegerField(blank=True, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(max_length=100)),
                ('fire_prevention_districts', models.IntegerField()),
                ('police_districts', models.IntegerField()),
                ('supervisor_districts', models.IntegerField()),
                ('zip_codes', models.CharField(max_length=10)),
                ('neighborhoods_old', models.IntegerField()),
            ],
        ),
    ]
