# Generated by Django 5.1 on 2024-08-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='facility_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
