# Generated by Django 5.1 on 2024-08-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_foodtruck_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='facility_type',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
    ]
