# Generated by Django 5.1 on 2024-08-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_foodtruck_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='applicant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='block',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='blocklot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='cnn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='facility_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='fire_prevention_districts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='food_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='locationId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='location_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='lot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='neighborhoods_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='permit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='police_districts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='schedule',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='supervisor_districts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='x_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='y_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='zip_codes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
