# Generated by Django 5.1 on 2024-08-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_foodtruck_approved_alter_foodtruck_permit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='applicant',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='food_items',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='schedule',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
