# Generated by Django 5.1 on 2024-08-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_foodtruck_applicant_alter_foodtruck_food_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='block',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='blocklot',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='location_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
