# Generated by Django 5.1 on 2024-08-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_foodtruck_block_alter_foodtruck_blocklot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='expiration_date',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='location',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
