# Generated by Django 5.1 on 2024-08-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_foodtruck_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='block',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='blocklot',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='lot',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='permit',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='status',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
