# Generated by Django 5.1 on 2024-08-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_foodtruck_block_alter_foodtruck_blocklot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
