# Generated by Django 5.1 on 2024-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_foodtruck_latitude_alter_foodtruck_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='blocklot',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
