# Generated by Django 5.1 on 2024-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_foodtruck_blocklot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='schedule',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
