# Generated by Django 5.1 on 2024-08-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_foodtruck_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='approved',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='days_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='expiration_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='facility_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='noi_sent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='received',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='zip_codes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
