# Generated by Django 5.1 on 2024-08-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_foodtruck_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='food_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
