# Generated by Django 5.1 on 2024-08-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_foodtruck_food_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='applicant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='block',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='blocklot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='location_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='lot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='permit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
